namespace: "netapp"
name: "azure"
version: "19.11.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: Azure NetApp Files (ANF)
repository: https://github.com/netapp/ansible/
homepage: netapp.io
tags:
    - "Storage"
    - "Cloud"
