namespace: "netapp"
name: "azure"
version: "21.9.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license_file: COPYING
readme: README.md
description: Azure NetApp Files (ANF)
dependencies:
    "azure.azcollection": ">=1.0.0"
repository: https://github.com/ansible-collections/netapp.azure
issues: https://github.com/ansible-collections/netapp.azure/issues
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - cloud
    - netapp
    - cvs
    - anf
    - azure
