namespace: "netapp"
name: "azure"
version: "20.8.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: Azure NetApp Files (ANF)
dependencies:
    "azure.azcollection": "*"
repository: https://github.com/ansible-collections/netapp
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - cloud
